name: Manual Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static
      RENDEZVOUS_SERVER: "187.124.13.191"
      RS_PUB_KEY: "F0QrJCreHax0mBClNCQ6BUC3G+Nq8IxF7WoGr1imGJc="
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: stable

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup vcpkg and Build Dependencies
        shell: pwsh
        run: |
          if (Test-Path $env:VCPKG_ROOT) { Remove-Item -Recurse -Force $env:VCPKG_ROOT }
          git clone https://github.com/microsoft/vcpkg $env:VCPKG_ROOT
          git -C $env:VCPKG_ROOT checkout 120deac3062162151622ca4860575a33844ba10b
          & "$env:VCPKG_ROOT\bootstrap-vcpkg.bat"
          & "$env:VCPKG_ROOT\vcpkg.exe" install --triplet x64-windows-static
          
          $targetPath = "$env:VCPKG_ROOT\installed\x64-windows-static"
          New-Item -ItemType Directory -Force -Path $targetPath
          Copy-Item -Path ".\vcpkg_installed\x64-windows-static\*" -Destination "$targetPath\" -Recurse -Force

      - name: Install FRB codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1 --features uuid --locked

      - name: Prepare Flutter packages
        shell: pwsh
        working-directory: ./flutter
        run: flutter pub get

      - name: Generate bridge files
        shell: pwsh
        run: |
          flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h
          Copy-Item "flutter/macos/Runner/bridge_generated.h" "flutter/ios/Runner/bridge_generated.h" -Force

      - name: Build
        shell: pwsh
        run: python build.py --flutter

      - name: Rename Executable
        shell: pwsh
        run: |
          if (Test-Path "target\release\rustdesk.exe") {
              Rename-Item -Path "target\release\rustdesk.exe" -NewName "See-Desk.exe"
              Write-Host "Renamed to See-Desk.exe successfully!"
          }

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: see-desk-windows
          path: |
            target/release/*.exe
            flutter/build/windows/**/*
