name: Manual Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk-org/vcpkg/releases/download/v1.0/vcpkg-x64-windows-static.zip" -OutFile "vcpkg.zip"
          Expand-Archive -Path "vcpkg.zip" -DestinationPath "C:\"
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.24.3'

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Codegen
        run: cargo install flutter_rust_bridge_codegen --version 1.80.1 --features uuid --locked

      - name: Generate bridge files
        run: |
          flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h
          Copy-Item "flutter/macos/Runner/bridge_generated.h" "flutter/ios/Runner/bridge_generated.h" -Force

      - name: Build Flutter Packages
        working-directory: ./flutter
        run: flutter pub get

      - name: Build Application
        run: python build.py --flutter

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: see-desk-windows
          path: |
            target/release/*.exe
            flutter/build/windows/**/*
